add_newline = false

[character]
success_symbol = '[âœ](bold green) '
error_symbol = '[âœ](bold red) '

[git_branch]
symbol = 'ğŸŒ± '

[git_status]
disabled = true

[directory]
truncate_to_repo = false
truncation_length = 36
truncation_symbol = 'â€¦/'

[nodejs]
format = 'via [ğŸ€ $version](bold green) '

[package]
disabled = true
